version: 2

jobs:
  build:backend-dev:
    docker:
      - image: circleci/node
    steps:
      # Enable Docker environment
      - setup_remote_docker
      # Fetch the source code
      - checkout
      # Log in to Docker Hub
      - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      # Build the image, tagging it as latest
      - run: docker build -t gurbaninow/api:${CIRCLE_SHA1} .
      # Push the image to Docker Hub
      - run: docker push gurbaninow/api:${CIRCLE_SHA1}
      # Tag the image as dev
      - run: docker tag gurbaninow/api:${CIRCLE_SHA1} gurbaninow/api:dev
      # Push the image to Docker Hub
      - run: docker push gurbaninow/api:dev

workflows:
  version: 2
  build:
    jobs:
      - build:backend-dev:
          filters:
            branches:
              only: dev
