name: Build and Publish Dev Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      run: docker build -t gurbaninow/api:${GITHUB_SHA} .
    - name: Publish
      run: |
        docker push gurbaninow/api:${GITHUB_SHA}
        docker tag gurbaninow/api:${GITHUB_SHA} gurbaninow/api:dev
        docker push gurbaninow/api:dev
