name: master

on:
  push:
    branches:
      - master

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build Docker Image
      run: docker build -t gurbaninow/api:${GITHUB_SHA} .
    - name: Publish to Docker Hub
      run: |
        docker push gurbaninow/api:${GITHUB_SHA}
        docker tag gurbaninow/api:${GITHUB_SHA} gurbaninow/api:latest
        docker push gurbaninow/api:latest
  build-github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.GITHUB_PERSONAL_TOKEN }} | docker login docker.pkg.github.com --username ${{ secrets.GITHUB_USERNAME }} --password-stdin
    - name: Build Docker Image
      run: docker build -t docker.pkg.github.com/gurbaninow/api/api:${GITHUB_SHA} .
    - name: Publish to GitHub Package Registry
      run: docker push docker.pkg.github.com/gurbaninow/api/api:${GITHUB_SHA}
